Provide an interface to se3-transformer
nlesc-nano/swan pull request #77
Opened 2021-03-24 11:48 UTC by felipeZ

## Changes
* Add [DGL](https://www.dgl.ai/) as a dependency
* Add [Se3-transformer](https://github.com/FabianFuchsML/se3-transformer-public) as a dependency
* Optionally compute a guess for the molecular positions using a force field (UFF) optimization

2021-03-29 09:10 UTC, NicoRenaud requested changes
Nice Job ! I've left a few minor comments. We should sit together and discuss the SE3 business. At the moment it's rather difficult for me to comment on that part as I have no idea what's happening :)

2021-03-29 09:10 UTC, NicoRenaud commented on swan/modeller/models/se3_transformer.py
> +    def __init__(self, num_layers: int, num_channels: int, num_nlayers: int = 1, num_degrees: int = 4):
docstrings ?

2021-03-29 09:10 UTC, NicoRenaud commented on swan/modeller/models/se3_transformer.py
> +    def __init__(self, num_layers: int, num_channels: int, num_nlayers: int = 1, num_degrees: int = 4):
in general I can't really comment on the code here as I don't know the architecture. As general comments, docstrings and typehints are missing. They might help understanding what's happening :)

2021-03-29 13:44 UTC, felipeZ commented on swan/dataset/fingerprints_data.py
> -    def get_item(batch_data: List[Any]) -> Tuple[torch.Tensor, torch.Tensor]:
I have moved it to the parent class because the methods in the children were doing almost the same.

2021-03-29 13:46 UTC, felipeZ commented on swan/dataset/dgl_graph_data.py
> +                 optimize_molecule: bool = False) -> None:
`properties` indeed need `Optional` but `file_geometries` doesn't need it because:
```py
Optional[T] = Union[T, None]
```

2021-03-29 13:47 UTC, felipeZ commented on swan/dataset/dgl_graph_data.py
> +class DGLGraphData(SwanDataBase):
I am going to make an experiment trying to remove the duplicate code as you have suggested.

2021-03-29 13:48 UTC, felipeZ commented on swan/dataset/features/featurizer.py
> +    atomic_features = np.zeros((number_atoms, NUMBER_ATOMIC_GRAPH_FEATURES), dtype=DTYPE)
thanks

2021-03-29 15:52 UTC, NicoRenaud commented on swan/dataset/dgl_graph_data.py
> +                 optimize_molecule: bool = False) -> None:
ha ok ! I didn't know that. I mainly wanted to be annoying with type hints 🤣

2021-03-29 15:53 UTC, NicoRenaud commented on swan/dataset/dgl_graph_data.py
> +class DGLGraphData(SwanDataBase):
Don't sweat over it, I'm not 100% sure it's needed.

2021-03-29 16:26 UTC, BvB93 commented on swan/utils/early_stopping.py
>      def __call__(self, saver: Callable, epoch: int, val_loss: float):
```suggestion
    def __call__(self, saver: Callable, epoch: int, val_loss: float) -> None:
```
FYI a function without an explicit return-type is equivalent to returning `Any`.

2021-03-30 07:27 UTC, felipeZ commented on swan/dataset/dgl_graph_data.py
> +        return self.molecular_graphs[idx], self.labels[idx]
I think the only difference is that  `__getitem__` returns a tuple for `DGLGraphDataset` and single object for torch version

2021-03-30 09:51 UTC, merged